#%RAML 1.0
title: HyperStorage API
baseUri: https://meta.inn.eu/hyperstorage
types:
  HyperStorageTransaction:
    type: object
    properties:
      transactionId: string

  HyperStorageTransactionCreated:
    type: object
    properties:
      transactionId: string
      path: string

  HyperStorageIndexSortOrder:
    enum: [asc, desc]

  HyperStorageIndexSortFieldType:
    enum: [string, decimal]

  HyperStorageIndexSortItem:
    type: object
    properties:
      fieldName: string
      fieldType: HyperStorageIndexSortFieldType
      order: HyperStorageIndexSortOrder

  HyperStorageIndex:
    type: object
    properties:
      indexId: string
      sort: HyperStorageIndexSortItem[]
      filter: string

  HyperStorageIndexNew:
    type: object
    properties:
      indexId?: string
      sort: HyperStorageIndexSortItem[]
      filter: string

  HyperStorageIndexCreated:
    type: object
    properties:
      indexId: string
      path: string

annotationTypes:
  feed:

/hyper-storage/content/{path:*}:
  uriParameters:
    path:*: string
  get:
    responses:
      200:
  put:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  patch:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  delete:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  post:
    responses:
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated

/hyper-storage/transactions/{transactionId}:
  uriParameters:
    transactionId: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction

/hyper-storage/indexes/{path:*}:
  uriParameters:
    path:*: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageIndex
  post:
    body:
      application/json:
        type: HyperStorageIndexNew
    responses:
      201:
        body:
          application/json:
            type: HyperStorageIndexCreated
  delete:
