#%RAML 1.0
title: Revault API
baseUri: https://meta.inn.eu/revault
types:
  RevaultTransaction:
    type: object
    properties:
      transactionId: string
  RevaultTransactionCreated:
      type: object
      properties:
        transactionId: string
        path: string
annotationTypes:
  feed:
/revault/content/{path:*}:
  uriParameters:
    path:*: string
  get:
    responses:
      200:
  put:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: RevaultTransaction
      201:
        body:
            application/json:
              type: RevaultTransactionCreated
  patch:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: RevaultTransaction
  delete:
    (feed):
    responses:
      200:
        body:
          application/json:
            type: RevaultTransaction
  post:
    responses:
      201:
        body:
            application/json:
              type: RevaultTransactionCreated
/revault/transactions/{transactionId}:
  uriParameters:
    transactionId: string
  get:
    responses:
      200:
        body:
          application/json:
            type: RevaultTransaction
